# Generated by Django 3.0.3 on 2020-06-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0003_company_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('telp', models.CharField(max_length=12)),
                ('id_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perusahaan.company')),
                ('id_privilege', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perusahaan.company_privileges')),
            ],
        ),
    ]
