# Generated by Django 3.0.3 on 2020-06-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0006_auto_20200623_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
