# Generated by Django 3.0.3 on 2020-06-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0007_remove_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='id_privilege',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='perusahaan.company_privileges'),
        ),
    ]
