# Generated by Django 3.0.3 on 2020-06-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0008_company_id_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id_privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perusahaan.company_privileges'),
        ),
    ]
