# Generated by Django 3.0.3 on 2020-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0015_auto_20200626_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_company',
        ),
        migrations.AddField(
            model_name='users',
            name='id_company',
            field=models.ManyToManyField(to='perusahaan.company'),
        ),
    ]
