# Generated by Django 3.0.3 on 2020-06-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0017_remove_users_id_privilege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
