# Generated by Django 3.0.3 on 2020-06-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0018_remove_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_company',
        ),
        migrations.AddField(
            model_name='users',
            name='id_company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='perusahaan.company'),
        ),
    ]
