# Generated by Django 3.0.3 on 2020-06-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0019_auto_20200630_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_company',
            field=models.CharField(max_length=254),
        ),
    ]
