# Generated by Django 3.0.3 on 2020-07-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0020_auto_20200630_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_company',
            field=models.IntegerField(),
        ),
    ]
