# Generated by Django 3.0.3 on 2020-07-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0022_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='presecne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('date_presence', models.DateField()),
                ('start_presence', models.TimeField()),
                ('end_presence', models.TimeField()),
                ('location', models.TextField(max_length=256)),
            ],
        ),
    ]
