# Generated by Django 3.0.3 on 2020-07-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0023_presecne'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='presecne',
            new_name='presence',
        ),
    ]
